[package]
name = "commande_groupe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
serde_json = "1.0.128"
serde_derive = "1.0.210"
serde = "1.0.210"